export {default as Navbar} from './navbar'
export {default as Menubar} from './menubar'
export {default as Contactbar} from './contactbar'
export {default as Home} from './home'
export {default as About} from './about'
export {default as Projects} from './projects'
export {default as ScrollButton} from './scrollbutton'
